version: 0.0
os: linux
files:
  - source:   /
    destination: /home/ec2-user/app/build/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall: #현재 단계에서 stop.sh 스크립트 파일을 실행시켜서 실행 중이던 스프링 부트 jar를 종료시킵니다.
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart: #start.sh 스크립트 파일을 실행시켜서 배포할 새로운 버전의 jar 파일을 실행시킵니다.
    - location: scripts/start.sh
      timeout: 60
      runas: root

  ValidateService: #health.sh 스크립트 파일을 통해서 현재 jar가 잘 실행 중인지 체크를 합니다.
    - location: scripts/health.sh
      timeout: 60
      runas: root